[[redirects]]
  from = "https://matic.razor.network/"
  to = "https://bridge.razor.network/#/matic"
  force = true

  [[redirects]]
  from = "http://matic.razor.network/"
  to = "https://bridge.razor.network/#/matic"
  force = true

[[redirects]]
  from = "https://skale.razor.network/"
  to = "https://bridge.razor.network/#/skale"
  force = true

[[redirects]]
  from = "http://skale.razor.network/"
  to = "https://bridge.razor.network/#/skale"
  force = true
