[[redirects]]
  from = "https://matic.razor.network/"
  to = "https://matic.razor.to/"
  force = true

[[redirects]]
  from = "https://skale.razor.network/"
  to = "https://skale.razor.to/"
  force = true
